;;; init.el --- Beatrix Klebe's Emacs init file -*- lexical-binding: t; -*-

;;; Commentary:
;;; This config borrows liberally from bbatsov's Emacs Prelude (https://github.com/bbatsov/prelude).

;;; Code:

(setq gc-cons-threshold 402653184
      gc-cons-percentage 0.6)

(defvar file-name-handler-alist-cache file-name-handler-alist)
(setq file-name-handler-alist nil)

(defvar root-dir (file-name-directory load-file-name)
  "The root of the current Emacs configuration.")

(defvar lisp-dir (expand-file-name "lisp" root-dir)
  "Location of my custom Lisp modules.")

(defvar autogen-dir (expand-file-name "autogen" lisp-dir)
  "Location for all automatically generated Lisp files.")

(defvar custom-storage-file (expand-file-name "custom.el" autogen-dir)
  "Where autogenerated custom.el settings go.")

(setq custom-file custom-storage-file)

(add-to-list 'load-path lisp-dir)

;;; This must be called first to setup use-package
(require 'package-config)

(require 'ui)
(require 'backup)
(when (eq system-type 'darwin) (require 'macos-config))
(when (eq system-type 'windows-nt) (require 'windows-config))

(require 'company-config)
(require 'flycheck-config)
(require 'editor)

(require 'development)

(require 'org-mode-config)

(setq gc-cons-threshold 16777216
      gc-cons-percentage 0.1)

(setq file-name-handler-alist file-name-handler-alist-cache)

(provide 'init)
;;; init.el ends here
